version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.6.0
    steps:
      - checkout
      - run:
          name: Install pypi Dependencies
          command: 
            echo 'export PATH=~$PATH~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip3 install -r requirements.txt

      - run:
          name: Run Unit Tests
          command: 
            python3 test_bot_info.py
      

    deploy:
      docker:
      - image: discordutilitybot/utilitybot/utilitybot:1.1
        auth:
        username: andrewisamazing1
        password: $DOCKERHUB_PASSWORD